// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Regenerate with `npm run routes` inside deploy/nas/rr-api.
import type { GeneratedRoute } from "./router";

import * as m0 from "../../../../functions/api/admin/installs/[id]/revoke";
import * as m1 from "../../../../functions/api/admin/licenses/[key]/activate";
import * as m2 from "../../../../functions/api/admin/licenses/[key]/bind";
import * as m3 from "../../../../functions/api/admin/licenses/[key]/revoke";
import * as m4 from "../../../../functions/api/admin/access/lift";
import * as m5 from "../../../../functions/api/admin/access/suspend";
import * as m6 from "../../../../functions/api/admin/licenses/issue";
import * as m7 from "../../../../functions/api/admin/licenses/search";
import * as m8 from "../../../../functions/api/discord/account/authorize";
import * as m9 from "../../../../functions/api/admin/announcements/[id]/index";
import * as m10 from "../../../../functions/api/admin/feedback/[id]/index";
import * as m11 from "../../../../functions/api/admin/licenses/[key]/index";
import * as m12 from "../../../../functions/api/discord/account/[action]";
import * as m13 from "../../../../functions/api/access/status";
import * as m14 from "../../../../functions/api/admin/access/index";
import * as m15 from "../../../../functions/api/admin/announcements/index";
import * as m16 from "../../../../functions/api/admin/customer-360";
import * as m17 from "../../../../functions/api/admin/customer-avatar";
import * as m18 from "../../../../functions/api/admin/customer-profiles";
import * as m19 from "../../../../functions/api/admin/feedback/index";
import * as m20 from "../../../../functions/api/admin/installs/index";
import * as m21 from "../../../../functions/api/admin/licenses/index";
import * as m22 from "../../../../functions/api/announcements/active";
import * as m23 from "../../../../functions/api/discord/callback";
import * as m24 from "../../../../functions/api/discord/oauth-start";
import * as m25 from "../../../../functions/api/discord/status";
import * as m26 from "../../../../functions/api/discord/verify";
import * as m27 from "../../../../functions/api/license/activate";
import * as m28 from "../../../../functions/api/license/validate";
import * as m29 from "../../../../functions/api/store/generate-key";
import * as m30 from "../../../../functions/api/usage/consume";
import * as m31 from "../../../../functions/api/usage/status";
import * as m32 from "../../../../functions/api/admin/data";
import * as m33 from "../../../../functions/api/admin/errors";
import * as m34 from "../../../../functions/api/admin/health";
import * as m35 from "../../../../functions/api/admin/sessions-export";
import * as m36 from "../../../../functions/api/admin/stats";
import * as m37 from "../../../../functions/api/admin/team";
import * as m38 from "../../../../functions/api/admin/user-activity";
import * as m39 from "../../../../functions/api/admin/users";
import * as m40 from "../../../../functions/api/admin/verify";
import * as m41 from "../../../../functions/api/auth/appearance";
import * as m42 from "../../../../functions/api/auth/bootstrap";
import * as m43 from "../../../../functions/api/auth/change-password";
import * as m44 from "../../../../functions/api/auth/login";
import * as m45 from "../../../../functions/api/auth/logout";
import * as m46 from "../../../../functions/api/auth/session";
import * as m47 from "../../../../functions/api/auth/watch";
import * as m48 from "../../../../functions/v1/telemetry/event";
import * as m49 from "../../../../functions/api/feedback/index";
import * as m50 from "../../../../functions/api/health";
import * as m51 from "../../../../functions/api/ingest";
import * as m52 from "../../../../functions/api/summary";

export const routes: GeneratedRoute[] = [
  { method: "POST", pattern: "/api/admin/installs/:id/revoke", handler: m0.onRequestPost },
  { method: "POST", pattern: "/api/admin/licenses/:key/activate", handler: m1.onRequestPost },
  { method: "POST", pattern: "/api/admin/licenses/:key/bind", handler: m2.onRequestPost },
  { method: "POST", pattern: "/api/admin/licenses/:key/revoke", handler: m3.onRequestPost },
  { method: "POST", pattern: "/api/admin/access/lift", handler: m4.onRequestPost },
  { method: "POST", pattern: "/api/admin/access/suspend", handler: m5.onRequestPost },
  { method: "POST", pattern: "/api/admin/licenses/issue", handler: m6.onRequestPost },
  { method: "GET", pattern: "/api/admin/licenses/search", handler: m7.onRequestGet },
  { method: null, pattern: "/api/discord/account/authorize", handler: m8.onRequest },
  { method: "DELETE", pattern: "/api/admin/announcements/:id", handler: m9.onRequestDelete },
  { method: "PUT", pattern: "/api/admin/announcements/:id", handler: m9.onRequestPut },
  { method: "DELETE", pattern: "/api/admin/feedback/:id", handler: m10.onRequestDelete },
  { method: "PUT", pattern: "/api/admin/feedback/:id", handler: m10.onRequestPut },
  { method: "DELETE", pattern: "/api/admin/licenses/:key", handler: m11.onRequestDelete },
  { method: "PATCH", pattern: "/api/admin/licenses/:key", handler: m11.onRequestPatch },
  { method: null, pattern: "/api/discord/account/:action", handler: m12.onRequest },
  { method: "POST", pattern: "/api/access/status", handler: m13.onRequestPost },
  { method: "GET", pattern: "/api/admin/access", handler: m14.onRequestGet },
  { method: "GET", pattern: "/api/admin/announcements", handler: m15.onRequestGet },
  { method: "POST", pattern: "/api/admin/announcements", handler: m15.onRequestPost },
  { method: "GET", pattern: "/api/admin/customer-360", handler: m16.onRequestGet },
  { method: "GET", pattern: "/api/admin/customer-avatar", handler: m17.onRequestGet },
  { method: "GET", pattern: "/api/admin/customer-profiles", handler: m18.onRequestGet },
  { method: "GET", pattern: "/api/admin/feedback", handler: m19.onRequestGet },
  { method: "GET", pattern: "/api/admin/installs", handler: m20.onRequestGet },
  { method: "GET", pattern: "/api/admin/licenses", handler: m21.onRequestGet },
  { method: "POST", pattern: "/api/admin/licenses", handler: m21.onRequestPost },
  { method: "GET", pattern: "/api/announcements/active", handler: m22.onRequestGet },
  { method: "GET", pattern: "/api/discord/callback", handler: m23.onRequestGet },
  { method: "GET", pattern: "/api/discord/oauth-start", handler: m24.onRequestGet },
  { method: "POST", pattern: "/api/discord/status", handler: m25.onRequestPost },
  { method: "POST", pattern: "/api/discord/verify", handler: m26.onRequestPost },
  { method: "POST", pattern: "/api/license/activate", handler: m27.onRequestPost },
  { method: "POST", pattern: "/api/license/validate", handler: m28.onRequestPost },
  { method: "GET", pattern: "/api/store/generate-key", handler: m29.onRequestGet },
  { method: "POST", pattern: "/api/store/generate-key", handler: m29.onRequestPost },
  { method: "POST", pattern: "/api/usage/consume", handler: m30.onRequestPost },
  { method: "GET", pattern: "/api/usage/status", handler: m31.onRequestGet },
  { method: null, pattern: "/api/access/status", handler: m13.onRequest },
  { method: null, pattern: "/api/admin/data", handler: m32.onRequest },
  { method: null, pattern: "/api/admin/errors", handler: m33.onRequest },
  { method: null, pattern: "/api/admin/health", handler: m34.onRequest },
  { method: null, pattern: "/api/admin/sessions-export", handler: m35.onRequest },
  { method: null, pattern: "/api/admin/stats", handler: m36.onRequest },
  { method: null, pattern: "/api/admin/team", handler: m37.onRequest },
  { method: null, pattern: "/api/admin/user-activity", handler: m38.onRequest },
  { method: null, pattern: "/api/admin/users", handler: m39.onRequest },
  { method: null, pattern: "/api/admin/verify", handler: m40.onRequest },
  { method: null, pattern: "/api/auth/appearance", handler: m41.onRequest },
  { method: null, pattern: "/api/auth/bootstrap", handler: m42.onRequest },
  { method: null, pattern: "/api/auth/change-password", handler: m43.onRequest },
  { method: null, pattern: "/api/auth/login", handler: m44.onRequest },
  { method: null, pattern: "/api/auth/logout", handler: m45.onRequest },
  { method: null, pattern: "/api/auth/session", handler: m46.onRequest },
  { method: null, pattern: "/api/auth/watch", handler: m47.onRequest },
  { method: null, pattern: "/v1/telemetry/event", handler: m48.onRequest },
  { method: "POST", pattern: "/api/feedback", handler: m49.onRequestPost },
  { method: null, pattern: "/api/health", handler: m50.onRequest },
  { method: null, pattern: "/api/ingest", handler: m51.onRequest },
  { method: null, pattern: "/api/summary", handler: m52.onRequest },
];
